[loggers]
keys=root,telegramBot,httpx,httpcore

[handlers]
keys=consoleHandler

[formatters]
keys=standardFormatter

[logger_root]
level=INFO
handlers=consoleHandler

[logger_telegramBot]
level=INFO
handlers=consoleHandler
qualname=__main__
propagate=0

[logger_httpx]
level=WARNING
handlers=consoleHandler
qualname=httpx
propagate=0

[logger_httpcore]
level=WARNING
handlers=consoleHandler
qualname=httpcore
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=standardFormatter
args=(sys.stdout,)

[formatter_standardFormatter]
format=%(asctime)s %(levelname)s %(name)s - %(message)s
